export const palette = {
  primary: '#004EFF',
  error: '#F44336',
  warn: '#FF9800',
  default: '#4A4A4A',
  success: '#4CAF50',
  background: '#FAFAFA',
  info: '#2196F3',
  accentBackground: '#FFFFFF',
};

export const OpertoTheme = {
  smartCards: {
    bg1: '#E8F0FE',
    bg2: '#3F51B5',
    bg3: '#008480',
    bg4: '#246FDB',
    bg5: '#38C5AB',
    bg6: '#0E33CC',
  },
  sideBarTextColor: '#5F6368',
  sideBarColor: '#E9F0FD',
  textColorWhite: '#FFFFFF',
  textColor: palette.default,
  textColorLight: '#A2AAAD',
  containerAccentBGColor: palette.accentBackground,
  containerBGColor: palette.background,
  containerDarkBGColor: '#f0f5f8',
  borderColor: '#E6EAF2',
  buttonPrimaryColor: palette.primary,
  tabColorActive: palette.primary,
  tabColor: palette.background,
  subHeaderBGColor: '#E6E9F1',
  subHeaderAltBGColor: '#E0E4EF',
  topBarColor: '#FFFFFF',
  palette,
  graphFillColor: '#E9F0FD',
  memberIconColor: '#FD612C',
  campaignIconColor: '#B81365',
  guestPortalIconColor: '#742DDD',
  radialBarBaseColor: '#EAEEF0',
  radialBarFirstBarColor: palette.primary,
  radialBarSecondBarColor: `${palette.primary}`,
};
