name: UI Library Production Deployment

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_BRANCH: ${{ github.ref_name }}
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Generate env
        run: |-
          cat > .env <<EOF
          REACT_APP_GIT_BRANCH=${{ env.GITHUB_BRANCH }}
          EOF

      - name: React Deploy to S3
        # You may pin to the exact commit or the version.
        uses: jeanlescure/react-deploy-to-s3-action@v1.1.0
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.PROD_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_ACCESS_SECRET }}
          SOURCE_DIR: build
          # Invalidate Cloudfront (this action)
      - name: invalidate
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.PROD_DISTRIBUTION }}
          PATHS: "/index.html"
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_ACCESS_SECRET }}
          AWS_REGION: "us-west-2"
